name: Auto-Rebase Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Fetch upstream changes
        run: git fetch origin

      - name: Rebase PR branch
        run: |
          git checkout ${{ github.head_ref }}
          git rebase origin/${{ github.base_ref }}
          git push --force-with-lease
