name: Auto-Rebase Pull Request

on:
  push:
    branches:
      - main

jobs:
  auto-rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Fetch open PR branches
        id: fetch_pr_branches
        run: |
          open_prs=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq -r '.[] | .number')
          for pr_branch in $open_prs; do
            echo "Fetching PR branch: ${pr_branch}"
            git fetch origin "refs/pull/${pr_branch}/head:refs/remotes/origin/pr/${pr_branch}"
          done
          echo "{pr_branches}={$open_prs}" >> $GITHUB_OUTPUT


   
      - name: Determine affected PRs
        id: determine_prs
        run: |
          echo 
          for pr_branch in ${ echo "${{ steps.fetch_pr_branches.outputs.pr_branches }}" }; do \
            echo "Checking PR branch: $pr_branch"; \
            if ! git merge-base --is-ancestor origin/main origin/pr/$pr_branch; then \
              echo "PR branch $pr_branch is out-of-date with main"; \
              echo "Rebasing $pr_branch onto main"; \
            fi; \
          done

