name: Auto-Rebase Pull Request

on:
  push:
    branches:
      - main

jobs:
  auto-rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Fetch pull request branches
        run: git fetch origin +refs/pull/*/head:refs/remotes/origin/pr/*

      - name: Determine affected PRs
        id: determine_prs
        run: |
          git for-each-ref --format='%(refname:short)' refs/remotes/origin/pr/* | \
            while read pr_branch; do \
              echo "Checking PR branch: $pr_branch"; \
              if ! git merge-base --is-ancestor origin/main $pr_branch; then \
                echo "PR branch $pr_branch is out-of-date with main"; \
                echo "Rebasing $pr_branch onto main"; \
                git checkout $pr_branch; \
                git rebase origin/main; \
                git push --force-with-lease; \
              fi; \
            done

