name: Auto-Rebase Pull Request

on:
  push:
    branches:
      - main

jobs:
  auto-rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      
      - name: Fetch pull request branches
        run: git fetch origin +refs/pull/*/head:refs/remotes/origin/pr/*

      - name: Determine affected PRs
        id: determine_prs
        run: |
          git for-each-ref --format='pr_branch=%(refname:short) base_ref=%(upstream:short)' refs/remotes/origin/pr/* | \
            while read entry; do \
              echo "Checking PR branch: $pr_branch and base ref: $base_ref"; \
              if git merge-base --is-ancestor "$base_ref" "origin/main"; then \
                echo "PR branch $pr_branch is out-of-date with main"; \
                echo "::set-output name=pr_branches::$pr_branch"; \
              fi; \
            done

      - name: Rebase affected PRs
        if: steps.determine_prs.outputs.pr_branches != ''
        run: |
          for pr_branch in $(echo "${{ steps.determine_prs.outputs.pr_branches }}"); do \
            echo "Rebasing $pr_branch onto main"; \
            git checkout $pr_branch; \
            git rebase origin/main; \
            git push --force-with-lease; \
          done